import p1 from './pics/1.jpg' 
import p2 from './pics/1920x1080 One Piece HD Luffy Cool Art 1080P Laptop Full HD Wallpaper, HD Anime 4K Wallpapers, Images, Photos and Background - Wallpapers Den.jpg' 
import p3 from './pics/2.jpg' 
import p4 from './pics/3.jpg' 
import p5 from './pics/4.jpg' 
import p6 from './pics/5.jpg' 
import p7 from './pics/6.jpg' 
import p8 from './pics/7.png' 
import p9 from './pics/ArtStation - Explore.jpg' 
import p10 from './pics/Athen Typeface.jpg' 
import p11 from './pics/Awesome Republic of Gamers 4K Wallpapers - WallpaperAccess.jpg' 
import p12 from './pics/background chiron.jpg' 
import p13 from './pics/background.jpg' 
import p14 from './pics/Blossoms by TacoSauceNinja on DeviantArt.jpg' 
import p15 from './pics/Bugatti chiron pur sport (2560x1600).jpg' 
import p16 from './pics/Cool wallpaper.jpg' 
import p17 from './pics/Desktop Wallpaper Warrior At Lake, Dark, Fantasy, Dragon, Art, Hd Image, Picture, Background, 752673.png' 
import p18 from './pics/dont touch my pc wallpaper by precioush on DeviantArt.jpg' 
import p19 from './pics/Download Asus Rog 4k Gaming Burning Logo Wallpaper Wallpapers_com.jpg' 
const file_name = [ p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 , p11 , p12 , p13 , p14 , p15 , p16 , p17 , p18 , p19 ,]
export default file_name